version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: example
        POSTGRES_DB: postgres
    volumes:
         - ./:/docker-entrypoint-initdb.d/
        
  adminer:
    image: adminer
    restart: always
    depends_on:
      - "db"
    ports:
      - 8080:8080
      
  myapp:
   image: myapp
   depends_on:
      - "db"
   command: javac -jar /myapp.jar --spring.batch.job.names=myapp-job
   
